name: Create repo

on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: What is the name of the repository?
        required: true
        default: ''

jobs:
  create_repo:
    name: Create new GitHub repo
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN:

    steps:
        - name: Check out repo
          uses: actions/checkout@v3
        - name: Create repo
          run: |
            echo "Repo name:" ${{ env.INPUT_REPO-NAME }}
            gh repo create ${{ env.INPUT_REPO-NAME }} --private
